-- MySQL Script generated by MySQL Workbench
-- Wed Apr 15 14:33:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema` DEFAULT CHARACTER SET utf8 ;
USE `sistema` ;

-- -----------------------------------------------------
-- Table `sistema`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `data_nascimento` VARCHAR(45) NULL,
  `logradouro` VARCHAR(45) NULL,
  `numero_logradouro` INT NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `data_nascimento` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`produtos` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `valor_produto` DECIMAL NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `quantidade` INT NULL,
  `forma_pagamento` VARCHAR(45) NULL,
  `valor` DECIMAL NULL,
  PRIMARY KEY (`id_venda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`item_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`item_venda` (
  `id_item_venda` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NULL,
  `valor` DECIMAL NULL,
  PRIMARY KEY (`id_item_venda`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
